spring:
  datasource:
    url: jdbc:h2:mem:frogcrew
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          authorities-claim-name: authorities
          authority-prefix: ""
api:
  endpoint:
    base-url: /api/v1